source: assets
destination: styleguide
documentation_assets: bower_components/Cortana

dependencies:
  - build/js
  - build/css
  - build/fonts

# To have a custom index page build with your README.md
index: README

# List all css to include for the styleguide render examples
css_include:
  - 'css/bootsketch.css'

# List all js to include for the styleguide render examples
js_include:
  - 'js/vendors.min.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '